### ISSUE TITLE
Fix preferredNamespaceUri value in ODRL Profile for Data Sovereignty

### ISSUE THREAD

**Issue by csarven** [Fraunhofer-IESE/ODS#10]
https://github.com/Fraunhofer-IESE/ODS/blob/2daae1ce57552ef696839ad66807af80e844f011/ods-profile.ttl#L25

the value should match the URI in https://github.com/Fraunhofer-IESE/ODS/blob/2daae1ce57552ef696839ad66807af80e844f011/ods-profile.ttl#L13

See also https://github.com/Fraunhofer-IESE/ODS/issues/9

**Comment by hosseinzadeha** [comment]
[https://w3id.org/ods/](https://w3id.org/ods/)
