### ISSUE TITLE
Fix ods w3.org namespace

### ISSUE THREAD

**Issue by csarven** [Fraunhofer-IESE/ODS#9]
The [current namespace of ods](https://github.com/Fraunhofer-IESE/ODS/blob/2daae1ce57552ef696839ad66807af80e844f011/ods.html#L683) is stated as `https://www.w3.org/ods/` however - to the best of my knowledge - W3C will not allocate anything top level as such. Namespaces are typically available from `http://www.w3.org/ns/`. So `http://www.w3.org/ns/ods/` may be possible. Please confirm with W3C staff / Team contacts and/or chairs of a W3C Group or W3C CG/BG (e.g., W3C ODRL CG) or other body in which ODS may be proposed through.

See also:
* https://www.w3.org/2005/07/13-nsuri
* https://github.com/w3c/ns/issues/2
* https://www.w3.org/2016/08/namespaces/

**Comment by hosseinzadeha** [comment]
[https://w3id.org/ods/](https://w3id.org/ods/)
